## Temporal Fusion Transformer: Time Series Forecasting with Deep Learning â€” Complete Tutorial
### Dummy introduction

In [2]:
import numpy as np
import pandas as pd
from pytorch_forecasting import TimeSeriesDataSet

In [3]:
sample_data = pd.DataFrame(
    dict(
        time_idx=np.tile(np.arange(6), 3),
        target=np.array([0,1,2,3,4,5,20,21,22,23,24,25,40,41,42,43,44,45]),
        group=np.repeat(np.arange(3), 6),
        holidays = np.tile(['X','Black Friday', 'X','Christmas','X', 'X'],3),
    )
)
sample_data

    time_idx  target  group      holidays
0          0       0      0             X
1          1       1      0  Black Friday
2          2       2      0             X
3          3       3      0     Christmas
4          4       4      0             X
5          5       5      0             X
6          0      20      1             X
7          1      21      1  Black Friday
8          2      22      1             X
9          3      23      1     Christmas
10         4      24      1             X
11         5      25      1             X
12         0      40      2             X
13         1      41      2  Black Friday
14         2      42      2             X
15         3      43      2     Christmas
16         4      44      2             X
17         5      45      2             X

In [6]:
dataset = TimeSeriesDataSet(
    sample_data,
    group_ids=['group'],
    target='target',
    time_idx="time_idx",
    max_encoder_length=2,
    max_prediction_length=3,
    time_varying_unknown_reals=["target"],
    static_categoricals=["holidays"],
    target_normalizer=None
)

In [7]:
dataloader = dataset.to_dataloader(batch_size=1)

In [9]:
#load the first batch
x, y = next(iter(dataloader))
print(x['encoder_target'])
print(x['groups'])
print('\n')
print(x['decoder_target'])

tensor([[21., 22.]])
tensor([[1]])


tensor([[23., 24., 25.]])